baseURL = "https://willdevforfood.github.io"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "WillDevForFood"
theme = "dream"
publishDir = "docs"

[params]
  enableSearch = true
  author = "WillDevForFood"
  headerTitle = "WillDevForFood"
  avatar = "/me/logo.png"
  favicon = "/logo.ico"

  github = "willdevforfood"

  siteStartYear = 2016

[outputs]
  home = ["HTML", "RSS", "JSON"]
